[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "Comics"
  url = "gallery"
  weight = 3


[[main]]
  identifier = "contact"
  name = "Contact"
  url = "contact"
  weight = 4


[[main]]
  identifier = "showcase"
  name = "More"
  weight = 5
  url = "showcase/"

[[main]]
  identifier = "quotes"
  name = "Quotes"
  url = "quotes"
  weight = 6

[[main]]
  identifier = "talks"
  name = "Talks"
  url = "talks"
  weight = 7
