[[main]]
  identifier = "about"
  name = "약"
  url = "about"
  weight = 1

[[main]]
  identifier = "talks"
  name = "회담"
  url = "talks"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "만화"
  url = "gallery"
  weight = 3

[[main]]
  identifier = "archive"
  name = "아카이브"
  url = "archive"
  weight = 4

[[main]]
  identifier = "showcase"
  name = "더"
  weight = 5
  url = "showcase/"
