[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 2

[[main]]
  identifier = "showcase"
  name = "More"
  weight = 3

[[main]]
  parent = "showcase"
  name = "Overview"
  url = "showcase/"
  weight = 1

[[main]]
  parent = "showcase"
  name = "Community"
  url = "showcase/community/"
  weight = 2

[[main]]
  parent = "showcase"
  name = "Online Editor"
  url = "showcase/online-editor/"
  weight = 3

[[main]]
  parent = "showcase"
  name = "Learning"
  url = "showcase/learn/"
  weight = 4

[[main]]
  parent = "showcase"
  name = "Sites"
  url = "showcase/sites/"
  weight = 5

[[main]]
  identifier = "gallery"
  name = "Comics"
  url = "gallery"
  weight = 6

[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 7