[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "Comics"
  url = "gallery"
  weight = 3


[[main]]
  identifier = "contact"
  name = "Contact"
  url = "contact"
  weight = 4

[[main]]
  name = "More"
  weight = 5
  
[[main]]
  parent = "More"
  identifier = "quotes"
  name = "Quotes"
  url = "More/quotes"

[[main]]
  parent = "gallery"
  identifier = "showcase"
  name = "Sites"
  weight = 5
  url = "More/showcase"

[[main]]
  parent = "More"
  identifier = "talks"
  name = "Talks"
  url = "More/talks"
