logoText = "Mistry Siddh"
logoType = "short" # long, short
description = "Get weakly news related to different kind of new, tips, tricks, etc. If you have your own theory or story then comment down in the post."
custom_css = []
custom_js = []
useFaviconGenerator = false # https://www.favicon-generator.org/
meta_image = "/images/whoami/avatar.png"
themecolor = "#212121"

themeOptions = ["light", "dark", "hacker", "solarized", "kimbie"]
notAllowedTypesInHome = ["contact", "talks", "about", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeSidebar = ["about", "archive", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInArchive = ["about", "talks", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeFeed = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]

viewportSize = "normal" # widest, wider, wide, normal, narrow
enableUiAnimation = true
hideSingleContentsWhenJSDisabled = true
enablePinnedPosts = true
minItemsToShowInTagCloud = 2 # Minimum items to show in tag cloud

# appbar
enableAppbarSearchIcon = true
enableAppbarLangIcon = false

# header
homeHeaderType = "text" # text, img, slide, typewriter
hideHomeHeaderWhenMobile = false

# menu
showMobileMenuTerms = ["tags", "categories", "series"]

# body
enableBreadcrumb = true
enablePhotoSwipe = true
enableSearch = true
enableSearchHighlight = true
enableGoToTop = true
enableWhoami = true
summaryShape = "classic" # card, classic, compact
searchResultPosition = "main" # side, main
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1
talksPaginate = 5
talksGroupByDate = "2006"
pubPaginate = 20
writtenTimeIcon = "📅"
modifiedTimeIcon = "📝"
readingTimeIcon = "☕"
authorIcon = "✍️"
pagePvIcon = "👀"
pinIcon = "📌"
tagIcon = "🏷️"
publicationIcon = "📚"
typeIcon = "🎯"

# whoami
myname = "Siddh Mistry"
email = "siddh.mistry396321@gmail.com"
whoami = "Blogger"
bioImageUrl = "/images/whoami/avatar.png"
useGravatar = false
location = "Valsad, Gujarat"
organization = ""
link = "https://mistrysiddh.tk"

# sidebar
enableBio = true
enableBioImage = true
enableSidebar = true
enableSidebarTags = true
enableSidebarSeries = true
enableSidebarCategories = true
enableHomeSidebarTitles = true
enableListSidebarTitles = true
enableToc = true
hideToc = false
tocFolding = true
tocPosition = "inner" # inner, outer
enableTocSwitch = true
itemsPerCategory = 5
sidebarPosition = "right"
tocLevels = ["h2", "h3", "h4"]
enableSidebarPostsByOrder = true

# footer
showPoweredBy = true
showFeedLinks = true
showSocialLinks = true
enableLangChange = false
enableThemeChange = true

# service
googleTagManager = "GTM-P6KBB6S" # GTM-XXXXXX
baiduAnalytics = ""
enableBusuanzi = true
busuanziSiteUV = true
busuanziSitePV = true
busuanziPagePV = true

# rss
updatePeriod = "daily" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
updateFrequency = ""
fullContents = false

# comment
enableComment = true
disqus_shortname = false
commento = true

[telegram]
  enable = false
  siteId = ""
  dataLimit = 5

[gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
  owner = "https://github.com/mrfoxie"              # Your GitHub ID
  repo = "https://github.com/mrfoxie/mistrysiddh"               # The repo to store comments
  clientId = "4f3d4f96c0fd763c3f61"           # Your client ID
  clientSecret = "b4523ce3bd70e81e7242aa4db279c3b032ad8a05"       # Your client secret

[utterances]       # https://utteranc.es/
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments

[gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
  owner = "https://github.com/mrfoxie"              # Your GitHub ID
  repo = "https://github.com/mrfoxie/mistrysiddh"               # The repo to store comments
  clientId = "5b932c2714c251e909e9"           # Your client ID
  clientSecret = "19a88099ca42474d3c0cf4864a02b9f47e836020"       # Your client secret

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[valine]
  enable = false
  appId = '你的appId'
  appKey = '你的appKey'
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mm' 
  placeholder = '说点什么吧...'
  visitor = false

[changyan]
  changyanAppid = ""        # Changyan app id             # 畅言
  changyanAppkey = ""       # Changyan app key

[livere]
  livereUID = ""            # LiveRe UID                  # 来必力

# Isso: https://posativ.org/isso/
[isso]
  enable = false
  scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
  dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[socialOptions]
  email = "mailto:siddh.mistry396321@gmail.com"
  phone = ""
  facebook = ""
  twitter = "http://twitter.com/Hacking_Tiger"
  github = "https://github.com/mrfoxie/mistrysiddh"
  stack-overflow = ""
  instagram = "https://instagram.com/mistrysiddh"
  google-plus = ""
  youtube = ""
  medium = ""
  tumblr = ""
  linkedin = "https://www.linkedin.com/in/SiddhMistry/"
  pinterest = "https://www.pinterest.com/siddhmistry/"
  stack-exchange = ""
  telegram = "https://t.me/MrFoxie"
  steam = ""
  weibo = ""
  douban = ""
  csdn = ""
  gitlab = ""
  mastodon = ""
  jianshu = ""
  zhihu = ""
  signal = ""
  whatsapp = "https://api.whatsapp.com/send?phone=916355040470&text=http%3A%2F%2Fmistrysiddh.tk%2F"
  matrix = ""
  xmpp = ""
  dev-to = ""
  gitea = ""
  google-scholar = ""

[donationOptions]
  enable = true
  alipay = "" 
  wechat = ""
  paypal = "https://paypal.me/mistrysiddh"
  patreon = "https://www.patreon.com/siddhmistry"

# possible share name: ["facebook","twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line", "pocket", "feedly", "hatena", "pinterest", "delicious", "google"]
[[share]]
  name = "facebook"
[[share]]
  name = "twitter"
  username = "Hacking_Tiger"
[[share]]
  name = "linkedin"
[[share]]
  name = "telegram"
[[share]]
  name = "reddit"
[[share]]
 name = "tumblr"
[[share]]
 name = "google"
#[[footerLinks]]
#  name = ""
#  link = ""
#[[footerLinks]]
#  name = ""
#  link = ""
