logoText = "Mistry Siddh"
logoType = "short" # long, short
description = "Get weakly news related to different kinds of news, tips, tricks, etc. If you have your own theory or story then comment down in the post."
custom_css = []
custom_js = []
useFaviconGenerator = false # https://www.favicon-generator.org/
meta_image = "/images/whoami/avatar.png"
themecolor = "#CCCCCC"

themeOptions = ["light", "dark", "hacker", "solarized", "kimbie"]
notAllowedTypesInHome = ["contact", "talks", "quotes", "about", "showcase", "publication", "presentation", "resume", "gallery"]
notAllowedTypesInHomeSidebar = ["about", "archive", "showcase", "publication", "presentation", "resume", "talks", "gallery"]
notAllowedTypesInArchive = ["about", "talks", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeFeed = ["about", "archive", "contact", "talks", "quotes", "showcase", "publication", "presentation", "resume", "gallery"]

viewportSize = "normal" # widest, wider, wide, normal, narrow
enableUiAnimation = true
hideSingleContentsWhenJSDisabled = true
enablePinnedPosts = true
minItemsToShowInTagCloud = 2 # Minimum items to show in tag cloud

# appbar
enableAppbarSearchIcon = true
enableAppbarLangIcon = false

# header
homeHeaderType = "img" # text, img, slide, typewriter
hideHomeHeaderWhenMobile = false

# menu
showMobileMenuTerms = ["categories", "series"]

# navbar
enableThemeChange = true

# body
enableBreadcrumb = true
enablePhotoSwipe = true
enableSearch = true
enableSearchHighlight = true
enableGoToTop = true
enableWhoami = true
summaryShape = "classic" # card, classic, compact
searchResultPosition = "main" # side, main
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1
talksPaginate = 5
talksGroupByDate = "2006"
pubPaginate = 20
writtenTimeIcon = "📅"
modifiedTimeIcon = "📝"
readingTimeIcon = "☕"
authorIcon = "✍️"
pagePvIcon = "👀"
pinIcon = "📌"
tagIcon = "🏷️"
publicationIcon = "📚"
typeIcon = "🎯"

# whoami
myname = "Mistry Siddh"
email = "siddh.mistry396321@gmail.com"
whoami = "Blogger"
bioImageUrl = "/images/whoami/avatar.png"
useGravatar = false
location = "Valsad, Gujarat"
organization = "Hello World!"
link = "https://www.mistrysiddh.tk"

# sidebar
enableBio = true
enableBioImage = true
enableSidebar = true
enableSidebarTags = true
enableSidebarSeries = true
enableSidebarCategories = true
enableHomeSidebarTitles = true
enableListSidebarTitles = true
enableToc = true
hideToc = false
tocFolding = true
tocPosition = "inner" # inner, outer
enableTocSwitch = true
itemsPerCategory = 5
sidebarPosition = "right"
tocLevels = ["h2", "h3", "h4"]
enableSidebarPostsByOrder = true

# footer
showPoweredBy = true
showFeedLinks = true
showSocialLinks = true
enableLangChange = false

# service
googleTagManager = "GTM-P5ZNLVH" # GTM-XXXXXX
googleRecaptcha = "6LesNi8aAAAAAGfQ6mXSkFJIVTpDpywrUUHTdxBj"
baiduAnalytics = ""
enableBusuanzi = true
busuanziSiteUV = true
busuanziSitePV = true
busuanziPagePV = true

# rss
updatePeriod = "hourly" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
updateFrequency = "1"
fullContents = true

# comment
enableComment = false
disqus_shortname = "siddhmistry"
commento = false

[telegram]
  enable = false
  siteId = ""
  dataLimit = 5

[socialOptions]
  email = "mailto:siddh.mistry396321@gmail.com"
  phone = ""
  facebook = ""
  twitter = ""
  github = "https://github.com/mrfoxie/mistrysiddh"
  stack-overflow = ""
  instagram = "https://instagram.com/mistrysiddh"
  google-plus = ""
  youtube = ""
  medium = ""
  tumblr = ""
  linkedin = "https://www.linkedin.com/in/SiddhMistry/"
  pinterest = "https://www.pinterest.com/siddhmistry/"
  stack-exchange = ""
  telegram = ""
  steam = ""
  weibo = ""
  douban = ""
  csdn = ""
  gitlab = ""
  mastodon = ""
  jianshu = ""
  zhihu = ""
  signal = ""
  whatsapp = "https://api.whatsapp.com/send?phone=916355040470&text=http%3A%2F%2Fmistrysiddh.tk%2F"
  matrix = ""
  xmpp = ""
  dev-to = ""
  gitea = ""
  google-scholar = ""

[donationOptions]
  enable = true
  alipay = "" 
  wechat = ""
  bitcoin = "" #122TFoeXM29qw1of2yPZntsVeZHKDbxTin
  paypal = "https://paypal.me/mistrysiddh"
  patreon = "https://www.patreon.com/siddhmistry"
  buymeacoffee = ""

[[share]]
  name = "facebook"
[[share]]
  name = "twitter"
  username = "Hacking_Tiger"
[[share]]
  name = "linkedin"
[[share]]
  name = "telegram"
[[share]]
  name = "reddit"
[[share]]
 name = "tumblr"
[[share]]
 name = "google"
[[share]]
 name = "whatsapp"
[[share]]
 name = "pocket"
[[share]]
 name = "feedly"
[[share]]
 name = "pinterest"
[[footerLinks]]
  name = "Muftsabazaar"
  link = "https://www.muftsabazaar.com"
[[footerLinks]]
  name = "Discord"
  link = "https://discord.gg/tfxN2Ws92Q"
