# Config for the Netlify Build Plugin: netlify-plugin-fetch-feeds
[[plugins]]
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    # Where should data files reside
    dataDir = "site/_data"

    # All the feeds we wish to gather for use in the build

    [[plugins.inputs.feeds]]
      name = "mistrysiddh"
      url = "https://www.mistrysiddh.tk/feed.json"
      ttl = 3600
    [[plugins.inputs.feeds]]
      name = "netlify"
      url = "https://www.mistrysiddh.tk/index.xml"
      ttl = 86400
