backend:	
  name: git-gateway	
  branch: master	
media_folder: static/images/
public_folder: /images/	
collections:	
  - name: 'posts'
    label: 'Posts'
    folder: '/content/en/posts'
    create: true	
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'	
    editor:	
      preview: true	
    fields:		
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Date', name: 'date', widget: 'datetime'}
      - {label: 'Draft', name: 'draft', widget: 'boolean'}
      - {label: 'HideToc', name: 'hideToc', widget: 'boolean'}
      - {label: 'EnableToc', name: 'enableToc', widget: 'boolean'}
      - {label: 'EnableTocContent', name: 'enableTocContent', widget: 'boolean'}
      - {label: 'Author', name: 'author', widget: 'string'}
      - {label: 'AuthorEmoji', name: 'authorEmoji', widget: 'string'}
      - {label: 'Pinned', name: 'pinned', widget: 'boolean'}
      - {label: 'Tags', name: 'tags', widget: 'list'}
      - {label: 'Categories', name: 'categories', widget: 'list'}
      - {label: 'Series', name: 'series', widget: 'list'}
      - {label: 'Feature Image', name: 'image', widget: 'string'}
      - { label: 'Body', name: 'body', widget: 'markdown'}
